CREATE TABLE IF NOT EXISTS account_warm_tip (
  id BIGSERIAL PRIMARY KEY,
  tip_type VARCHAR(32) NOT NULL,
  content_zh VARCHAR(160) NOT NULL,
  content_en VARCHAR(240) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_account_warm_tip_status_sort ON account_warm_tip (status, sort);
CREATE INDEX IF NOT EXISTS idx_account_warm_tip_deleted_at ON account_warm_tip (deleted_at);

INSERT INTO account_warm_tip (id, tip_type, content_zh, content_en, sort, status) VALUES
(1, 'quote', '行到水穷处，坐看云起时', 'Walk where waters end, then sit calmly and watch the clouds arise', 10, 1),
(2, 'quote', '明月松间照，清泉石上流', 'Moonlight shines through pines, while clear springs flow over stones', 20, 1),
(3, 'quote', '空山新雨后，天气晚来秋', 'After fresh rain in empty hills, evening air carries autumn clarity', 30, 1),
(4, 'quote', '大漠孤烟直，长河落日圆', 'A lone desert smoke rises straight as the long river meets sunset', 40, 1),
(5, 'quote', '独坐幽篁里，弹琴复长啸', 'Sitting alone among quiet bamboo, play the qin and breathe freely', 50, 1),
(6, 'quote', '深林人不知，明月来相照', 'Deep within the forest, unseen by people, moonlight still arrives', 60, 1),
(7, 'quote', '劝君更尽一杯酒，西出阳关无故人', 'Drink one more cup before the western road grows lonelier', 70, 1),
(8, 'quote', '渭城朝雨浥轻尘，客舍青青柳色新', 'Morning rain settles dust, and guesthouse willows shine newly green', 80, 1),
(9, 'quote', '白云回望合，青霭入看无', 'White clouds gather behind, while blue mist disappears when approached', 90, 1),
(10, 'quote', '江流天地外，山色有无中', 'The river flows beyond heaven and earth, mountains fade between seen and unseen', 100, 1),
(11, 'quote', '长风破浪会有时，直挂云帆济沧海', 'Great winds will break waves someday, so raise sails toward vast seas', 110, 1),
(12, 'quote', '天生我材必有用，千金散尽还复来', 'Born with useful talent, even spent gold may one day return', 120, 1),
(13, 'quote', '仰天大笑出门去，我辈岂是蓬蒿人', 'Laugh toward heaven and step outside, refusing a small and timid life', 130, 1),
(14, 'quote', '两岸猿声啼不住，轻舟已过万重山', 'Though cries echo from both shores, the light boat passes countless mountains', 140, 1),
(15, 'quote', '飞流直下三千尺，疑是银河落九天', 'A waterfall plunges three thousand feet, like the Milky Way descending', 150, 1),
(16, 'quote', '桃花潭水深千尺，不及汪伦送我情', 'Deep peach waters cannot match the warmth of a true farewell', 160, 1),
(17, 'quote', '浮云游子意，落日故人情', 'Drifting clouds hold traveler thoughts, sunset carries old friendship', 170, 1),
(18, 'quote', '俱怀逸兴壮思飞，欲上青天揽明月', 'With bold delight and rising thoughts, reach toward moonlit skies', 180, 1),
(19, 'quote', '人生得意须尽欢，莫使金樽空对月', 'When life opens brightly, enjoy fully and do not waste moonlit cups', 190, 1),
(20, 'quote', '相看两不厌，只有敬亭山', 'Looking without weariness, only quiet mountains keep steady company', 200, 1),
(21, 'quote', '知行合一，从眼前一事认真做起', 'Unite knowledge and action by doing the present task with care', 210, 1),
(22, 'quote', '此心光明，亦复何言，先把当下做好', 'When the heart is bright, fewer words are needed than steady action', 220, 1),
(23, 'quote', '破山中贼易，破心中贼难', 'Defeating outer trouble is easier than mastering restless thoughts within', 230, 1),
(24, 'quote', '心即理也，向内澄明再向外做事', 'Principle lives in the heart; clarify within before acting outward', 240, 1),
(25, 'quote', '志不立，天下无可成之事', 'Without a settled will, no meaningful work can truly be completed', 250, 1),
(26, 'quote', '人须在事上磨，方能立得住', 'People are tempered through real matters before they can stand firm', 260, 1),
(27, 'quote', '静处体悟，事上练心，日用常行', 'Reflect in quiet, train the heart in work, practice daily', 270, 1),
(28, 'quote', '去山中之贼易，去心中之贼难', 'Clearing thieves from mountains is easier than clearing the heart', 280, 1),
(29, 'quote', '只念念要存天理，即是立志', 'Keeping right principle in each thought is already a form of resolve', 290, 1),
(30, 'quote', '致良知于事事物物，便是修行', 'Extending conscience through every matter is a practical path of cultivation', 300, 1),
(31, 'positive', '尽量让每一天都过的有意义~', 'To make each day count!', 310, 1),
(32, 'positive', '把眼前小事做好，远方自然慢慢清楚', 'Do the small thing well, and distant direction becomes clearer', 320, 1),
(33, 'positive', '今日多走一步，明日就少一点慌张', 'Take one more step today, and tomorrow begins with less panic', 330, 1),
(34, 'positive', '心里有光，手上有事，脚下就有路', 'With light inside and work in hand, the road appears underfoot', 340, 1),
(35, 'positive', '先稳住呼吸，再稳住节奏，事情就会推进', 'Steady your breath first, then rhythm, and work begins moving', 350, 1),
(36, 'positive', '把复杂拆成一段一段，难题就有了边界', 'Break complexity into parts, and hard problems gain clear edges', 360, 1),
(37, 'positive', '别急着证明自己，先把结果认真做出来', 'Do not rush to prove yourself, first produce careful results', 370, 1),
(38, 'positive', '今日有所得，哪怕很小，也值得记下', 'If today brings one gain, however small, it deserves remembering', 380, 1),
(39, 'positive', '愿你心有山河，仍能低头做好细节', 'May your heart hold mountains while your hands finish details', 390, 1),
(40, 'positive', '把时间放在重要处，生活会给出回声', 'Put time where it matters, and life will answer in echoes', 400, 1),
(41, 'rest', '远看窗外云影，让眼睛和念头一起放松', 'Look at clouds beyond the window, letting eyes and thoughts relax', 410, 1),
(42, 'rest', '起身慢走几步，像山风穿过空林一样轻', 'Stand and walk slowly, light as mountain wind through empty woods', 420, 1),
(43, 'rest', '喝一口温水，给忙碌的心留一点余地', 'Drink warm water and leave a little space for the busy heart', 430, 1),
(44, 'rest', '闭眼片刻听呼吸，回来时再看问题本身', 'Close your eyes and hear breathing, then return to the problem', 440, 1),
(45, 'rest', '松开肩颈与眉头，今日不必一直绷紧', 'Release shoulders and brows; today does not require constant tension', 450, 1),
(46, 'rest', '让屏幕远一点，让身心都重新找到距离', 'Move the screen farther away and let body and mind regain distance', 460, 1),
(47, 'rest', '整理桌面三分钟，也整理下一步的方向', 'Clear your desk for three minutes, and clarify the next direction', 470, 1),
(48, 'line', '愿此刻像明月照松间，清澈而不喧哗', 'May this moment shine like moonlight through pines, clear and quiet', 480, 1),
(49, 'line', '愿你像轻舟过万山，压力再多也向前', 'May you pass many mountains like a light boat, still moving forward', 490, 1),
(50, 'line', '愿心中有良知，手上有行动，日日见光', 'May conscience guide the heart, action fill the hands, and days brighten', 500, 1)
ON CONFLICT (id) DO UPDATE SET
  tip_type = EXCLUDED.tip_type,
  content_zh = EXCLUDED.content_zh,
  content_en = EXCLUDED.content_en,
  sort = EXCLUDED.sort,
  status = EXCLUDED.status,
  updated_at = CURRENT_TIMESTAMP;
SELECT setval(pg_get_serial_sequence('account_warm_tip', 'id'), GREATEST((SELECT COALESCE(MAX(id), 1) FROM account_warm_tip), 1), true);
